# Custom Resource Definitions for External Secrets Operator
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
  labels:
    app.kubernetes.io/name: external-secrets
spec:
  group: external-secrets.io
  names:
    kind: ExternalSecret
    listKind: ExternalSecretList
    plural: externalsecrets
    singular: externalsecret
    shortNames:
    - es
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              secretStoreRef:
                type: object
                properties:
                  name:
                    type: string
                  kind:
                    type: string
              target:
                type: object
                properties:
                  name:
                    type: string
                  creationPolicy:
                    type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    secretKey:
                      type: string
                    remoteRef:
                      type: object
                      properties:
                        key:
                          type: string
                        property:
                          type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretstores.external-secrets.io
  labels:
    app.kubernetes.io/name: external-secrets
spec:
  group: external-secrets.io
  names:
    kind: SecretStore
    listKind: SecretStoreList
    plural: secretstores
    singular: secretstore
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              provider:
                type: object
                properties:
                  vault:
                    type: object
                  kubernetes:
                    type: object
                  fake:
                    type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersecretstores.external-secrets.io
  labels:
    app.kubernetes.io/name: external-secrets
spec:
  group: external-secrets.io
  names:
    kind: ClusterSecretStore
    listKind: ClusterSecretStoreList
    plural: clustersecretstores
    singular: clustersecretstore
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              provider:
                type: object
                properties:
                  vault:
                    type: object
                  kubernetes:
                    type: object
                  fake:
                    type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterexternalsecrets.external-secrets.io
  labels:
    app.kubernetes.io/name: external-secrets
spec:
  group: external-secrets.io
  names:
    kind: ClusterExternalSecret
    listKind: ClusterExternalSecretList
    plural: clusterexternalsecrets
    singular: clusterexternalsecret
    shortNames:
    - ces
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              externalSecretSpec:
                type: object
                properties:
                  secretStoreRef:
                    type: object
                    properties:
                      name:
                        type: string
                      kind:
                        type: string
                  target:
                    type: object
                    properties:
                      name:
                        type: string
                      creationPolicy:
                        type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        secretKey:
                          type: string
                        remoteRef:
                          type: object
                          properties:
                            key:
                              type: string
                            property:
                              type: string
              externalSecretName:
                type: string
              externalSecretMetadata:
                type: object
                properties:
                  annotations:
                    type: object
                    additionalProperties:
                      type: string
                  labels:
                    type: object
                    additionalProperties:
                      type: string
              namespaceSelector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
                  matchExpressions:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          type: array
                          items:
                            type: string
              refreshTime:
                type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
              externalSecretName:
                type: string
              failedNamespaces:
                type: array
                items:
                  type: object
                  properties:
                    namespace:
                      type: string
                    reason:
                      type: string
              provisionedNamespaces:
                type: array
                items:
                  type: string