# Individual application definition - Redis App
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-redis-app
  namespace: argocd
  labels:
    managed-by: app-of-apps
    app-type: database
spec:
  project: default
  
  source:
    repoURL: https://github.com/SinaDadvand/gitops-argocd.git
    targetRevision: HEAD
    path: gitops-apps/redis-app
  
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-redis
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true