# Regular Kubernetes secret template (DO NOT commit this to Git)
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: production-app
type: Opaque
data:
  username: YWRtaW4=  # admin (base64)
  password: UGFzc3cwcmQxMjM=  # Passw0rd123 (base64)
  host: cG9zdGdyZXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs  # postgresql.production.svc.cluster.local
  port: NTQzMg==  # 5432
  database: UUFfZW52X2Ri  # production_db