apiVersion: v1
kind: ConfigMap
metadata:
  name: production-app-config
  namespace: production-app
  labels:
    app: production-app
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Production App - Sealed Secrets Demo</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 0;
                padding: 20px;
                background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
                color: white;
                min-height: 100vh;
            }
            .container {
                max-width: 1200px;
                margin: 0 auto;
                background: rgba(255, 255, 255, 0.1);
                padding: 40px;
                border-radius: 15px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            }
            .header {
                text-align: center;
                margin-bottom: 40px;
            }
            .header h1 {
                font-size: 3em;
                margin-bottom: 10px;
                background: linear-gradient(45deg, #fff, #f0f0f0);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
            }
            .security-badge {
                display: inline-block;
                padding: 10px 20px;
                background: #27ae60;
                border-radius: 25px;
                font-weight: bold;
                margin: 10px 5px;
            }
            .info-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
                gap: 20px;
                margin-top: 30px;
            }
            .info-card {
                background: rgba(0, 0, 0, 0.3);
                padding: 25px;
                border-radius: 15px;
                border: 1px solid rgba(255, 255, 255, 0.2);
            }
            .info-card h3 {
                color: #3498db;
                margin-bottom: 15px;
                font-size: 1.3em;
            }
            .secret-item {
                margin: 10px 0;
                padding: 10px;
                background: rgba(0, 0, 0, 0.2);
                border-radius: 8px;
                border-left: 4px solid #27ae60;
            }
            .secret-masked {
                font-family: 'Courier New', monospace;
                background: #2c3e50;
                padding: 3px 8px;
                border-radius: 4px;
                color: #ecf0f1;
            }
            .secret-env {
                font-family: 'Courier New', monospace;
                background: #27ae60;
                padding: 3px 8px;
                border-radius: 4px;
                color: white;
                font-weight: bold;
            }
            .status-indicator {
                display: inline-block;
                width: 12px;
                height: 12px;
                border-radius: 50%;
                margin-right: 8px;
            }
            .status-ok { background: #2ecc71; }
            .status-warning { background: #f39c12; }
            .endpoints {
                margin-top: 30px;
                text-align: center;
            }
            .endpoints a {
                color: #3498db;
                text-decoration: none;
                margin: 0 15px;
                padding: 8px 16px;
                border: 1px solid #3498db;
                border-radius: 20px;
                transition: all 0.3s;
            }
            .endpoints a:hover {
                background: #3498db;
                color: white;
            }
            .env-demo {
                background: rgba(39, 174, 96, 0.1);
                border: 1px solid #27ae60;
                padding: 15px;
                border-radius: 8px;
                margin-top: 15px;
            }
            .env-demo h4 {
                color: #27ae60;
                margin-top: 0;
            }
        </style>
        <script>
            function maskSecret(value, prefixLength = 4) {
                if (!value) return '****';
                return value.substring(0, prefixLength) + '****';
            }
            
            function updateStatus() {
                document.getElementById('timestamp').textContent = new Date().toLocaleString();
                
                // Simulate checking sealed secrets status
                const secretsStatus = document.getElementById('secrets-status');
                secretsStatus.innerHTML = '<span class="status-indicator status-ok"></span>All secrets decrypted successfully';
                
                // Update connection status
                const dbStatus = document.getElementById('db-status');
                dbStatus.innerHTML = '<span class="status-indicator status-ok"></span>Database connection ready';
                
                const apiStatus = document.getElementById('api-status');
                apiStatus.innerHTML = '<span class="status-indicator status-ok"></span>API keys loaded from environment';
                
                // Show environment variable information
                updateEnvInfo();
            }
            
            function updateEnvInfo() {
                // Note: In a real application, these would come from server-side endpoints
                // For demo purposes, we show what the environment variables would contain
                const envInfo = document.getElementById('env-info');
                envInfo.innerHTML = `
                    <h4>🔍 Environment Variables Status:</h4>
                    <p><strong>DB_HOST:</strong> <span class="secret-env">Set from sealed secret ✓</span></p>
                    <p><strong>DB_USERNAME:</strong> <span class="secret-env">Set from sealed secret ✓</span></p>
                    <p><strong>STRIPE_API_KEY:</strong> <span class="secret-env">Set from sealed secret ✓</span></p>
                    <p><strong>GITHUB_TOKEN:</strong> <span class="secret-env">Set from sealed secret ✓</span></p>
                    <p><strong>JWT_SECRET:</strong> <span class="secret-env">Set from sealed secret ✓</span></p>
                    <small>💡 Run 'kubectl exec deployment/production-app -- printenv | grep -E "DB_|STRIPE_|GITHUB_|JWT_"' to see actual values</small>
                `;
            }
            
            setInterval(updateStatus, 10000);
            window.onload = updateStatus;
        </script>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🔐 Production Application</h1>
                <p>Demonstrating Sealed Secrets Integration with GitOps</p>
                <div class="security-badge">🛡️ Sealed Secrets Enabled</div>
                <div class="security-badge">🔒 GitOps Secure</div>
            </div>
            
            <div class="info-grid">
                <div class="info-card">
                    <h3>🔑 Sealed Secrets Status</h3>
                    <div class="secret-item">
                        <strong>Controller Status:</strong><br>
                        <span id="secrets-status">Loading...</span>
                    </div>
                    <div class="secret-item">
                        <strong>Encryption:</strong> RSA-2048<br>
                        <strong>Namespace Scoped:</strong> Yes<br>
                        <strong>Auto-rotation:</strong> 30 days
                    </div>
                </div>
                
                <div class="info-card">
                    <h3>🗄️ Database Configuration</h3>
                    <div class="secret-item">
                        <strong>Host:</strong> <span class="secret-masked">postgresql.production.svc****</span><br>
                        <strong>Database:</strong> <span class="secret-masked">production_****</span><br>
                        <strong>Username:</strong> <span class="secret-masked">admin****</span><br>
                        <strong>Status:</strong> <span id="db-status">Checking...</span>
                    </div>
                </div>
                
                <div class="info-card">
                    <h3>🔗 API Integrations</h3>
                    <div class="secret-item">
                        <strong>Stripe API:</strong> <span class="secret-masked">sk_test****</span><br>
                        <strong>GitHub Token:</strong> <span class="secret-masked">ghp_****</span><br>
                        <strong>SendGrid:</strong> <span class="secret-masked">SG.****</span><br>
                        <strong>JWT Secret:</strong> <span class="secret-masked">****</span><br>
                        <strong>Status:</strong> <span id="api-status">Validating...</span>
                    </div>
                </div>
                
                <div class="info-card">
                    <h3>🛠️ GitOps Security Features</h3>
                    <div class="secret-item">
                        ✅ Secrets encrypted at rest in Git<br>
                        ✅ Public key encryption (RSA)<br>
                        ✅ Namespace-scoped decryption<br>
                        ✅ Automatic secret rotation<br>
                        ✅ ArgoCD integration<br>
                        ✅ Audit trail maintained
                    </div>
                </div>
            </div>
            
            <div class="env-demo">
                <div id="env-info">Loading environment variable status...</div>
            </div>
            
            <div class="endpoints">
                <h3>🔗 Application Endpoints</h3>
                <a href="/health">Health Check</a>
                <a href="/ready">Ready Check</a>
                <a href="/metrics">Metrics</a>
                <a href="/config">Configuration</a>
            </div>
            
            <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.2);">
                <p><strong>🔐 Sealed Secrets Benefits:</strong></p>
                <p>• Store encrypted secrets safely in Git • Maintain GitOps principles • Automatic decryption in cluster • Key rotation support</p>
                <p><small>Last updated: <span id="timestamp"></span> | Environment: Production | Security: High</small></p>
            </div>
        </div>
    </body>
    </html>
  health: "OK"
  ready: "READY"