# Production application that uses sealed secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-app
  namespace: production-app
  labels:
    app: production-app
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      securityContext:
        runAsNonRoot: false
      # Init container to install dependencies
      initContainers:
      - name: npm-install
        image: node:18-alpine
        workingDir: /tmp/app
        command: ["sh", "-c"]
        args:
        - |
          echo "Copying application files..."
          cp -r /app-source/* /tmp/app/
          echo "Installing dependencies..."
          npm install --production
          echo "Dependencies installed successfully"
          echo "Copying to shared volume..."
          cp -r /tmp/app/* /app-runtime/
          echo "Init container completed"
        volumeMounts:
        - name: config
          mountPath: /app-source
          readOnly: true
        - name: app-runtime
          mountPath: /app-runtime
      containers:
      - name: app
        image: node:18-alpine
        workingDir: /app
        command: ["sh", "-c"]
        args: 
        - |
          echo "Starting Node.js application..."
          echo "Files in /app:"
          ls -la /app/
          echo "Starting server..."
          node app.js
        ports:
        - containerPort: 3000
          name: http
        env:
        # Database connection using sealed secrets
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        # API keys using sealed secrets
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: stripe-api-key
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: github-token
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: sendgrid-api-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: jwt-secret
        # Application configuration
        - name: APP_ENV
          value: "production"
        - name: APP_VERSION
          value: "1.0.0"
        volumeMounts:
        - name: app-runtime
          mountPath: /app
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: production-app-config
      - name: app-runtime
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: production-app-service
  namespace: production-app
  labels:
    app: production-app
spec:
  selector:
    app: production-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30130
  type: NodePort


