# ArgoCD Application for External Secrets Operator (Alternative GitOps approach)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets
    component: security
    managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Install before secret stores
spec:
  project: default
  
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.11
    chart: external-secrets
    helm:
      values: |
        # Core configuration
        installCRDs: true
        image:
          tag: v0.9.11
        
        # Webhook configuration
        webhook:
          port: 9443
          create: true
        
        # Certificate controller
        certController:
          create: true
          
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          
        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
            
        # High availability
        replicaCount: 1
        
        # Service monitor for Prometheus (if using)
        serviceMonitor:
          enabled: false
        
        # Metrics configuration
        metrics:
          service:
            enabled: true
            port: 8080
        
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true  # Handle large CRDs
    
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m