# ArgoCD Application for Production App with Sealed Secrets
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-app-sealed-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: production-app
    environment: production
    security-level: high
    secrets-type: sealed
spec:
  project: default
  
  source:
    repoURL: https://github.com/SinaDadvand/gitops-argocd.git
    targetRevision: HEAD
    path: gitops-apps/production-app
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m