# ArgoCD Application for Sealed Secrets Controller
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: sealed-secrets-controller
    component: security
    managed-by: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/SinaDadvand/gitops-argocd.git
    targetRevision: HEAD
    path: gitops-apps/sealed-secrets
  
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m