apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: personal-redis
data:
  redis.conf: |
    # Redis configuration for development
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000